# H2 Konsole im Browser aktivieren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datenbank-Verbindung (läuft komplett im RAM deines PCs während der Entwicklung)
spring.datasource.url=jdbc:h2:mem:gymtrackerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# SQL-Befehle lesbar im IntelliJ-Terminal anzeigen
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update